<section>
    <form id="signup-form">
        <label for="new-email">Email:</label>
        <input type="email" id="new-email" name="email" placeholder="Email" required>
        <label for="new-password">Password:</label>
        <input type="password" id="new-password" name="password" placeholder="Password" required>
        <label for="confirm-password">Confirm Password:</label>
        <input type="password" id="confirm-password" name="confirm-password" placeholder="Confirm Password" required>
        <p class="error hidden">username or password is invalid</p>
        <button id="signup-submit">Sign Up</button>
    </form>
</section>