<section>
    <p>Welcome to the Budgeting App! Please log in or create an account to get started.</p>
    <form id="login-form">
        <label for="email">Email:</label>
        <input type="email" id="email" placeholder="Email" required>
        <label for="password">Password:</label>
        <input type="password" id="password" placeholder="Password" required>
        <p class="error hidden">username or password is not correct</p>
        <button id="login-submit">Login</button>
    </form>
    <p>Don't have an account? <a href="/app/create-account">Create one here</a>.</p>
</section>